### PR TITLE
Update database for 2.5 and 2.6

### PR DESCRIPTION
**Pull request by bschouwerwou**
Just getting the database updated for the upcoming 2.6 release.

There's a couple of things left that I'll be able to do once 2.6 is out:
- [x] confirm auxiliary drops from new artifact domain
- [x] add new world boss
- [x] use better images

### CODE REVIEW

**Review by luaneko — APPROVED** [review]
Thanks for this! LGTM for now.

I think I will cherry-pick the 2.5 update into master just because we're so behind on that update. I'll leave this PR for 2.6.

**Comment by luaneko** [comment]
Actually on second thought, since 2.6 update is happening in less than two days anyway, maybe we'll wait a little bit more...

**Comment by bschouwerwou** [comment]
@phosphene47 should be good to go now!

**Review by luaneko — APPROVED** [review]
LGTM

**Pull request merged**
