### PR TITLE
Add realm currency calculator

### PR DESCRIPTION
**Pull request by ysc3839**
Screenshot: 
image

### CODE REVIEW

**Comment by luaneko** [comment]
I made some improvements to your PR:

image

- Some UI improvements
- Fixed textbox not being dynamically sized
- Abstracted away textbox autosize logic from the calculator for code reuse
- Added an estimator and a clear button
- Ensured all inputs are validated and clamped in the possible ranges

If everything looks good after reviewing, please mark it as approved and I will merge!

**Comment by Primajin** [comment]
Nice, really looking forward to this 🚀

**Comment by ysc3839** [comment]
> please mark it as approved

I can't find an "approve" button.
Are you just asking if I approve these changes? This is your project, so I have no question with your changes.

**Comment by luaneko** [comment]
> I can't find an "approve" button.

I'm talking about "Approve Changes" button in the review pull request page. If you can't find it, no worries.

> Are you just asking if I approve these changes? This is your project, so I have no question with your changes.

It doesn't hurt to have multiple reviewers even if it's the owner's code. I can make mistakes and introduce bugs too ;)

**Pull request merged**
