### PR TITLE
Realm currency steps

### LINKED ISSUE #70: Show realm currency steps and sync with the resin estimator
The resin calculator has the great way of switching between time and value based estimation:
 

While the recently added realm currency currently only shows one value:

I would wish for something similar in terms of estimation - at best synced with the setting of resin:

(mockup)

_I'll try to take a stab at it._

### PR DESCRIPTION
**Pull request by Primajin**
Closes: https://github.com/chiyadev/genshin-schedule/issues/70

~~:construction: WORK IN PROGRESS :construction:~~ Ready for review

tmi
Too much information?

responsive

### CODE REVIEW

**Comment by Primajin** [comment]
Anything missing that I may help with?

**Comment by luaneko** [comment]
> Anything missing that I may help with?

Sorry for the lack of response! I was really busy with other personal things and wasn't able to access my PC for the entire week.

I'll make sure to review this PR in the next few days, since I'll be home 24/7 now thanks to restarting lockdown in my state ;)

**Comment by Primajin** [comment]
Oh no sad to hear that, stay healthy! 🤞🏻 😷

**Review by luaneko — APPROVED** [review]
This looks really good!

I made one small change that makes estimations by time start from 2 hours instead of 1 hour to stay consistent with the behavior of resin estimations.

**Comment by Primajin** [comment]
Sweet thanks! Yeah I wasn't sure if we wanted it more consistent or more focused - I'm happy with both.

**Comment by Primajin** [comment]
Actually 1hr makes no sense at all, since the user already puts in what they get per hour 😜

**Pull request merged**
