### PR TITLE
Add resin mode switcher to settings

### LINKED ISSUE #47: [Feature Request] Alternate Resin timing
The Resin calculator is super handy - I use it all the time. But it would be even more helpful if it could also show (or be set to show) when you'll hit relevant amounts of resin (as opposed to how much resin you'll have in certain amounts of time). Basically, how long until you hit any given multiple of 20 so you know when you can hit your next domain, boss, etc.

This would be even better if you could set your time zone and see what time you'll hit these milestones, and best of all if you could set reminders for them with the reminders bot (ping me whenever I have 40 resin available, for instance)

### PR DESCRIPTION
**Pull request by Primajin**
Closes #47

# Off
off
off-2
# On
on
on-2

### CODE REVIEW

**Comment by luaneko** [comment]
I didn't fully understand what the issue was saying until you submitted this PR 🤦

It's actually already possible to switch between the estimation modes by clicking on the resin icon left to the calculator, but a setting like this would make it more explicit.

I don't think a switch is the right component though; in terms of UX, I think a select with "By time" and "By value" would be more appropriate. What do you think?

**Comment by Primajin** [comment]
Yes that sounds better, will change that!

**Comment by Primajin** [comment]
How about this:
image

**Review by luaneko — APPROVED** [review]
LGTM

**Comment by luaneko** [comment]
> Ahh thanks, I couldn't find a configured linter - shall we add eslint / prettier or something alike in the future?

If you are using vscode, I think it should automatically detect Prettier? It's already installed and configured for this repository.

**Comment by Primajin** [comment]
Ah I'm on Webstorm, thanks maybe I forgot to turn it on correctly

**Pull request merged**
