### PR TITLE
Use defaultMessage instead of id to translate

### PR DESCRIPTION
**Pull request by ysc3839**

### CODE REVIEW

**Comment by ysc3839** [comment]
There is still some entries with id. I put them in `langs/static.json`.
I think we need a script to manage the translation files.

**Comment by luaneko** [comment]
[Discord message link](https://discord.com/channels/786573740875841566/797858372866146315/838608021176844338)

I discussed about this PR on Discord with BiliGoldenWater who had some concerns about using automatic extraction.

### Hashes are not descriptive of the message content

It's friendlier for translators when they see `resinTitle` instead of a hash like `fxk59ds`. The descriptive ID gives an idea of where the message is being used in the UI ("resin" and "title") which can be helpful.

### Hash changes when the original text changes

If a message in the `en-US` localization changes, the message ID changes together which renders the translation of this message in all other localizations unusable and fall back to `en-US` until updated by the translators again.

### Localization files should not be splitted

Having multiple files for a single localization (like `en-US.json` and `static.json` in this PR) makes it incompatible with online translation platforms.

## Counterargument

This PR uses FormatJS `extract` which actually does support explicit IDs. So in theory we can use explicit IDs as well as automatic extraction. But the point of automatic extraction is to avoid manually specifying IDs. So the benefit of a hybrid approach is questionable.

I'm not sure what the best approach is, and I don't know how other large projects handle localization. If you can input your opinion, that would be great!

**Comment by ysc3839** [comment]
1. Hashes are not descriptive of the message content
These hashes are not for translators, they are only for program. The translators see only original texts and translated texts.
2. Hash changes when the original text changes
Yes, but I don't think it's a problem. Translations is needed to maintain. If using ID, when the meaning of original text changed but translation remains unchanged, this may cause problem.
3. Localization files should not be splitted
This PR is still working in progress. This should be disscussed.

The main problem of using ID is you have to manually manage the `ID -> text` relations, which is easy to make errors and cost times.

There's many translate system. But macOS Cocoa, GNU gettext and Qt are using messages instead of ID. I don't know why they choose this, but I think they have their consideration.

**Comment by ysc3839** [comment]
Added extract script to generate po file.

**Comment by ysc3839** [comment]
Added generate script to generate json file from po file.

**Comment by ysc3839** [comment]
I think this PR is done.
When trnslating, use `yarn extract` to extract translatable strings to template file `en-US.pot`.
Then you can use tools like [Poedit](https://poedit.net/) to translate.
After translate you get `lang-code.po` (For example: `zh-CN.po`), use `yarn genlangs` to generate `lang-code.json`.

**Comment by ysc3839** [comment]
Also names of characters, artifacts... should be added to a file, in order to allow generate script add them to the template file.

**Comment by ysc3839** [comment]
Fixed merge conflicts.

**Review by luaneko — CHANGES_REQUESTED** [review]
There is a significant problem with the extraction: it ignores duplicate `defaultMessage` because of their equal hashes, even though the messages can have different semantic meaning in their respective contexts.

For example, there is a message "Submit" in the login page which means to log in, translating to "登录".

image

However there is another instance of "Submit" in the account manager modal which means to change/save, translating to "保存".

image

This extractor does not allow translating both instances separately because the hash ID generated from "Submit" is the same, and duplicate entries are removed, leaving only one in the `.pot` file:

```po
#: components/Customize/SettingsList/AccountManageButton.tsx:129
msgctxt "wSZR47"
msgid "Submit"
msgstr ""
```

**Comment by ysc3839** [comment]
@phosphene47 Yes. In such case you have to specific an ID manually.

**Review by luaneko — APPROVED** [review]
I made some changes to this PR to address the duplicate message issue described in my comment above, and small code quality improvements.

- Appended source path to `msgctxt` to ensure duplicate messages from different files are added to the `.pot` properly.

> en-US.pot

image

image

This also addresses the concern of hashes not being descriptive of the message they represent, by prefixing the source path in the ID.

- Removed `static.json` and hardcoded the values into code using a `switch` statement. There weren't many unit messages in the first place, so I believe this reduces complexity without introducing too much redundancy.

> time.tsx

image

- Reformatted all affected files. Please use prettier to format files next time! (vscode can do it automatically on save with an extension)

**Pull request merged**
